### ISSUE TITLE
Need 'backup' user to have uid=801,gid=801 and 'backup' group have gid=801 for consistency across hosts.

### ISSUE THREAD

**Issue by bdgregg** [ulsdevteam/ansible-build#5]
https://github.com/ulsdevteam/ansible-build/blob/1dc314c760596e9a684724a07744131a7775c6b5/ojs.yml#L101

Eg.
$ id backup
uid=801(backup) gid=801(backup) groups=801(backup)

**Comment by ctgraham** [comment]
Dup of https://github.com/ulsdevteam/ansible-build/issues/4
